
const Privacidad = () => {
    return (
        <div className="terminos">
        <div className="term-title">Políticas de Privacidad</div>
        <div className="term-subtitle">Por favor, lea atentamente la siguiente Política de Privacidad que tiene como objetivo fijar las pautas de protección de privacidad establecidas por Chelas S.A., CUIT 30-00000000-2, con domicilio en Ciudad Autónoma de Buenos Aires, Argentina (en adelante, la “Empresa”), en el territorio de la República Argentina, así como  informarle qué datos e información se obtendrán por su registro y utilización del Sitio conforme a las finalidades establecidas en los Términos y Condiciones por Usted aceptados. La presente Política de Privacidad es obligatoria y debe ser expresamente aceptada por Usted para poder hacer uso del Sitio. Todas y cualquiera de las actividades consistentes en el acceso, uso, visitas, navegación, registración y/o confirmación electrónica de las transacciones realizadas a través del Sitio, se encuentran sujetas a la aceptación y el consentimiento expreso del Usuario. Deberá abstenerse de utilizar el Sitio quien no acepte la presente Política de Privacidad. La Empresa informa que todos los datos que Usted proporcione a la Empresa se encontrarán sujetos a la presente Política de Privacidad.</div>
        <div className="term-spacer"></div>
        <div>
            <div className="term-subtitle">PRIMERA: Respeto por la Privacidad.</div>
            <div className="term-text">La Empresa respeta la privacidad de todos los Usuarios que ingresan, usan, navegan y/o se registran en el Sitio.</div>
            <div className="term-text">Por tal razón, la Política de Privacidad establece cuál es la información personal de los Usuarios (en adelante, la “Información”) que la Empresa puede recopilar, el uso y finalidad que se le dará a la Información, las medidas de seguridad adoptadas por la Empresa, los mecanismos puestos a disposición de los Usuarios para que accedan a la Información sobre cómo contactar a la Empresa para consultar sobre la aplicación de la Política de Privacidad y/o sobre cualquier otra cuestión que pudiera surgir al respecto.</div>
            <div className="term-spacer"></div>
        </div>
        <div>
            <div className="term-subtitle">SEGUNDA: Recopilación y uso de la información de los usuarios.</div>
            <div className="term-text">El Usuario que no desee que la Empresa recopile la Información sobre él, debe abstenerse de navegar por el Sitio y/o registrarse como Usuario.</div>
            <div className="term-text">El Usuario conoce, comprende y acepta que la Información será objeto de tratamiento automatizado e incorporada a la base de datos de la Empresa a los fines que se indican a continuación: procesar la Información para comprender mejor las necesidades de los Usuarios; mejorar las prestaciones y los servicios de la Empresa; elaborar estadísticas; permitir que la Empresa se comunique con el Usuario; facturar los productos ofrecidos por la Empresa a través del Sitio; organizar, diseñar, elaborar, segmentar y/o dirigir promociones publicitarias, acciones de marketing, venta directa y/o otras actividades análogas y/o para cualquier otro fin que fuera estrictamente necesario a efectos de que la Empresa pueda brindar sus servicios al Usuario.</div>
            <div className="term-text">La Empresa informa que los servicios mencionados anteriormente podrán ser prestados en forma directa por la Empresa y/o a través de terceros contratados a tales efectos. En estos casos, la relación con los terceros contratados se regirá conforme la cláusula 3 de la presente.</div>
            <div className="term-text">En consecuencia, cada vez que el Usuario le brinde Información a la Empresa, el Usuario acepta y presta su consentimiento libre, expreso e informado para que la Información sea utilizada con las finalidades arriba mencionadas, y autoriza a que la misma sea tratada, almacenada, recopilada o cedida conforme a los términos y condiciones establecidos en la Política de Privacidad.</div>
            <div className="term-text">La Empresa recopila Información a través del Sitio cuando: i) cualquier visitante ingresa y navega por el Sitio; ii) se envían preguntas, reclamos, comentarios o mensajes a la Empresa; iii) se completa el proceso de registro del Usuario; iv) se solicita material informativo sobre el Sitio o alguna de sus actividades; y/o v) se participa de promociones, concursos o encuestas en línea.</div>
            <div className="term-text">La Información puede incluir nombre, apellido, dirección, sexo, edad, número de identidad, dirección de correo electrónico, teléfono, profesión, código de identificación tributaria (C.U.I.T.) y/o información sobre la condición impositiva y previsional necesaria para que la Empresa pueda facturar sus servicios, y/o o cualquier otra información que permita individualizar al Usuario.</div>
            <div className="term-spacer"></div>
        </div>
        <div>
            <div className="term-subtitle">TERCERA: Cesión de información a terceros.</div>
            <div className="term-text">El Usuario conoce, comprende y acepta que la Empresa transfiera sus datos a sus afiliadas, controladas, vinculadas, relacionadas y/o a cualquier tercero, aun cuando éstos se encuentren en países que no tengan los mismos niveles de privacidad que la Argentina, cuando esto fuera estrictamente necesario a efectos de cumplir con alguno de los fines indicados en la cláusula 2 de la presente Política de Privacidad.</div>
            <div className="term-text">La Información será revelada, compartida o cedida de acuerdo con la legislación vigente en la República Argentina aplicable a la protección de datos personales, asegurando la confidencialidad y privacidad de la Información del Usuario.</div>
            <div className="term-text">La Empresa informa al Usuario que se compromete a tomar todas las medidas que estuvieran a su alcance a efectos de asegurar que estas empresas y/o terceros apliquen medidas de privacidad y confidencialidad adecuadas en el tratamiento de la Información, y que éstos utilicen la misma exclusivamente para los fines para los que ha sido cedida. Además, estos terceros deberán eliminar y/o devolver a la Empresa la Información que les hubiera sido suministrada cuando ya no fuera necesaria a los fines a los que hubiera sido compartida.</div>
            <div className="term-text">La Empresa podrá revelar la Información en los siguientes casos, siempre que estuviera permitido por la ley: (a) si fuese requerida por una autoridad judicial o administrativa nacional, provincial, municipal y/o cualquier otro organismo público que fuera competente; (b) si dichos datos fueran necesarios para la protección de derechos de terceros; (c) cuando fuese necesario para la protección de los derechos o intereses de la Empresa sus controlantes, controladas, vinculadas, directores, gerentes, empleados, los Usuarios o el público en general.</div>
            <div className="term-spacer"></div>
        </div>
        <div>
            <div className="term-subtitle">CUARTA: Envío de correos electrónico al usuario.</div><div className="term-text">La Empresa podrá enviar correos electrónicos al Usuario a efectos de informar sobre las transacciones realizadas a través del mismo, y/o el estado de su cuenta. Asimismo, podrá utilizarlo para enviar notificaciones de la Empresa al Usuario y/o responder a las preguntas y/o consultas del Usuario.</div><div className="term-text">La Empresa también podrá enviar correos electrónicos con información, ofertas o promociones sobre los productos, y servicios ofrecidos.</div><div className="term-text">En todo momento el Usuario podrá solicitar a la Empresa ser dado de baja de la lista de distribución comunicándose a la dirección de email que se indique en el correo electrónico que envíe la Empresa.</div>
            <div className="term-spacer"></div>
        </div>
        <div>
            <div className="term-subtitle">QUINTA: Uso de cookies y otras tecnologías.</div><div className="term-text">Al aceptar la presente Política de Privacidad, el Usuario da su consentimiento para que la Empresa almacene información en su computadora, bajo la forma de una "Cookie" o tecnologías similares. Las Cookies permiten diseñar e implementar mejoras que permitan satisfacer en mayor medida los intereses y preferencias de usuarios y visitantes. La mayoría de los sitios de internet hacen uso de estas cookies, suministrando información que puede ser utilizada para dar seguimiento y ofrecer contenido concreto adecuado a los intereses de cada visitante.</div><div className="term-text">Las cookies no causan daños a la computadora y únicamente el Sitio podrá leerlas, almacenarlas, modificarlas y/o eliminarlas.</div><div className="term-text">Se informa al Usuario que la mayoría de los programas de navegación para Internet permiten borrar las Cookies del disco rígido de su computadora, bloquear todas las Cookies o recibir un mensaje de alerta antes de que se almacene una Cookie.</div><div className="term-text">La Empresa recomienda al Usuario consultar las instrucciones de su programa de navegación para saber cómo funcionan y se aplican estas funciones.</div><div className="term-text">En caso de que el Usuario no desee autorizar el uso de las cookies por parte de la Empresa, solicitamos se abstenga de navegar por el Sitio.</div><div className="term-text">La aceptación de la Política de Privacidad también implicará que el Usuario presta su consentimiento para que la Empresa recopile información técnica en forma automática, tal como el tipo de sistema de navegación por internet utilizado por el Usuario, sistema operativo de su computadora, y otros datos vinculados a su sistema de acceso a Internet.</div>
            <div className="term-spacer"></div>
        </div>
        <div>
            <div className="term-subtitle">SEXTA: Medidas de privacidad.</div><div className="term-text">La Empresa ha dispuesto medios físicos, electrónicos, administrativos y procedimientos de seguridad para resguardar y asegurar la Información, prevenir el acceso no autorizado a la misma, mantener la precisión de los datos y asegurar el uso correcto de la Información.</div><div className="term-text">La Empresa resguarda la Información de acuerdo a estándares y procedimientos de seguridad reconocidos y aceptados en el mercado y permanentemente analiza cómo mejorar y elevar los niveles de protección de la Información.</div><div className="term-text">Sin perjuicio de lo expuesto en el párrafo precedente, el Usuario reconoce que los medios técnicos existentes de seguridad no son inexpugnables, y que aun cuando se adopten todos los recaudos razonables de seguridad es posible sufrir manipulaciones, destrucción y/o pérdida de datos o de la Información. Sin embargo, la Empresa garantiza que tomará todas las medidas que estuvieran a su alcance para proteger a los Usuarios frente a cualquier modificación, divulgación y/o acceso no autorizado de la Información que conserve.</div><div className="term-text">Por otra parte, el Usuario queda advertido que también es responsable de adoptar las medidas de seguridad necesarias para proteger la Información, tales como mantener en secreto su clave de acceso al Sitio, cambiar la clave de acceso periódicamente, utilizar claves de acceso de seguridad que incluyan combinación de letras y números, utilizar un sistema de navegación seguro y no acceder al Sitio desde redes públicas, locutorios y/u otros lugares que no garanticen la seguridad en el acceso al Sitio o el tráfico de datos.</div><div className="term-text">LA AGENCIA DE ACCESO A LA INFORMACIÓN PÚBLICA, en su carácter de Órgano de Control de la Ley N° 25.326, tiene la atribución de atender las denuncias y reclamos que interpongan quienes resulten afectados en sus derechos por incumplimiento de las normas vigentes en materia de protección de datos personales.</div>
            <div className="term-spacer"></div>
        </div>
        <div>
            <div className="term-subtitle">SÉPTIMA: Derechos del titular de los datos.</div><div className="term-text">De conformidad con la legislación vigente, se informa al Usuario que podrá solicitar el ejercicio de su derecho de acceso, rectificación o supresión de la Información en forma gratuita en intervalos no inferiores a seis meses, salvo que se acredite un interés legítimo al efecto conforme lo establecido en el artículo 14, inciso 3 de la Ley Nº 25.326, mediante el envío de un correo electrónico a la dirección indicada en el párrafo debajo, previa acreditación de su identidad.</div><div className="term-text">Si la Información es incorrecta y el Usuario desea corregirla, actualizarla y/o suprimirla, la Empresa procederá conforme sea la solicitud del Usuario sin costo alguno.</div><div className="term-text">Toda solicitud de actualización y/o supresión de la Información debe ser dirigida a la siguiente dirección de correo electrónico contacto@tada.com.ar indicando en el asunto del correo "Informar", "Rectificar", "Suprimir" y/o "Actualizar" según corresponda y proveyendo los datos necesarios para cumplir con el objeto del requerimiento.</div><div className="term-text">Sin perjuicio de lo expuesto, la Empresa podrá conservar la Información o datos cuya eliminación hubiera sido solicitada si existiera una obligación legal de conservar los datos o una orden emanada de autoridad judicial o administrativa competente en dicho sentido.</div>
            <div className="term-spacer"></div>
        </div>
        <div>
            <div className="term-subtitle">OCTAVA: Información acerca de terceros.</div><div className="term-text">El Usuario podrá enviar a la Empresa información acerca de terceros a efectos de participar en alguna promoción, sorteo, descuento y/o cualquier otra actividad o servicio que así lo requiera, conforme sea indicado en los términos y condiciones de cada producto, siempre que dicha información se limite a información mínima para la cual no resulte necesario el consentimiento del tercero.</div><div className="term-text">La Empresa informa que utilizará dicha información exclusivamente a los fines para los cuales dicha información fue enviada. En ese caso, la Empresa podrá enviar información y mensajes publicitarios sobre sus productos y servicios a los terceros. En este caso, estos terceros podrán hacer uso de la opción de no recibir correos electrónicos comunicando dicha decisión a la Empresa.</div><div className="term-text">El Usuario asume toda responsabilidad por eventuales perjuicios o lesiones a derechos de terceros que se derive de la entrega de Información de terceros a la Empresa, y mantendrá indemne a la Empresa respecto de cualquier reclamo que dichos terceros puedan plantear a la Empresa.</div>
            <div className="term-spacer"></div>
        </div>
        <div>
            <div className="term-subtitle">NOVENA: Plug in sociales.</div>
            <div className="term-text">La Empresa informa que el Sitio contiene plug in sociales (los “Plug In”) que permiten al usuario conectar el Sitio con diferentes redes sociales. De este modo, el usuario podrá indicar que le gusta el Sitio en redes sociales como Facebook, sin tener que salir del Sitio y/o compartir sus experiencias con sus amigos y otros usuarios de dichas redes sociales.</div><div className="term-text">Del mismo modo, mediante el Plug In el Sitio dará la posibilidad al usuario de iniciar sesión y registrarse como Usuario ingresando a través de alguna cuenta creada con anterioridad en otra red social (tal como Facebook, Instagram, y/ cualquiera que allí se indique).</div><div className="term-text">La Empresa informa que mediante el uso de los Plug In se podrá compartir cierta información del Usuario que fuera necesaria para que los Plug In puedan cumplir con la finalidad antes indicada.</div>
            <div className="term-spacer"></div>
        </div>
        <div>
            <div className="term-subtitle">DÉCIMA: Cambios a la Política de Privacidad.</div><div className="term-text">La Empresa se reserva el derecho a modificar la Política de Privacidad en el momento, términos y/ o condiciones que la Empresa considere pertinente, conforme los principios y requisitos establecidos en la Ley No. 25.326.</div><div className="term-text">Dichos cambios tendrán vigencia a partir del momento mismo en que sean publicados en el Sitio o desde que sean notificados al Usuario por cualquier medio, lo que ocurra primero.</div><div className="term-text">La Empresa recomienda verificar la Política de Privacidad cada vez que se acceda al Sitio.</div>
            <div className="term-spacer"></div>
        </div>
        <div>
            <div className="term-subtitle">DÉCIMA PRIMERA: Contacto de la empresa.</div><div className="term-text">Cualquier Usuario o visitante del Sitio puede enviar consultas sobre la Política de Privacidad o su Información mediante el envío de un correo electrónico: contacto@tada.com.ar.</div>
            <div className="term-spacer"></div>
        </div>
        <div>
            <div className="term-subtitle">DÉCIMA SEGUNDA: Legislación y jurisdicción aplicables.</div><div className="term-text">La Política de Privacidad se rige por la legislación vigente en la República Argentina, y todo conflicto sobre su aplicación e interpretación queda sometida a la jurisdicción y competencia de jurisdicción de los Tribunales Ordinarios en lo Comercial de la Ciudad de Buenos Aires, con exclusión de cualquier otro fuero o jurisdicción que pudiera corresponder.</div><div className="term-text">Última actualización: 15 de abril de 2021.</div>
            <div className="term-spacer"></div>
        </div>
        </div>
    )
};

export default Privacidad;