
const Terminos = () => {
    return (
        <>
        <div className="terminos">
            <div className="term-title">Términos y Condiciones</div>
            <div className="term-title">Contratos de adhesión - Ley N° 24.240 de Defensa del Consumidor</div>
            <div className="term-spacer"></div>
                <div>
                    <div className="term-subtitle">General</div>
                    <div className="text">El único idioma oficial de estos Términos y Condiciones es el español. Este sitio web http://www.chelas.com.ar y su aplicación móvil (en adelante, el “Sitio”) es operado por Chelas S.A., CUIT 30-000000000-2, con domicilio en Ciudad Autónoma de Buenos Aires, Argentina (en adelante, la “Empresa”). Por favor, lea atentamente los siguientes términos y condiciones y reglas básicas que rigen el acceso, uso, transacciones y demás servicios en y/o a través del Sitio (en adelante los “Términos y Condiciones”). Por ello, estos Términos y Condiciones y la Política de Privacidad (en adelante, la “Política de Privacidad”) son obligatorios, y deben ser expresamente aceptados por Usted para poder hacer uso del Sitio. Toda y cualquiera de las actividades consistentes en el acceso, uso, visitas, navegación, registración y/o confirmación electrónica de las transacciones realizadas a través del Sitio, se encuentran sujetas a la aceptación y el consentimiento expreso del Usuario (definido más abajo) de los Términos y Condiciones y la obligación de cumplirlos acabadamente. Deberá abstenerse de utilizar el Sitio quien no acepte los Términos y Condiciones. La compra de productos y artículos ofrecidos en el Sitio se encuentra sujeta a disponibilidad de stock, sin derecho a reclamo de ninguna índole en caso de agotarse el mismo.</div><div className="term-text">Toda y cualquiera de las actividades consistentes en el acceso, uso, visitas, navegación, registración y/o confirmación electrónica de las transacciones realizadas a través del Sitio, se encuentran sujetas a la aceptación y el consentimiento expreso del Usuario (definido más abajo) de los Términos y Condiciones y la obligación de cumplirlos acabadamente. Deberá abstenerse de utilizar el Sitio quien no acepte los Términos y Condiciones.</div>
                    <div className="term-text">Sólo podrán ser Usuarios las personas humanas mayores de 18 años, que posean capacidad legal para contratar y que no tengan ningún impedimento según las leyes de la Argentina para utilizar este Sitio (en adelante, el “Usuario”). Todos los cargos, precios y costos de los servicios de internet necesarios para el acceso, uso, visita, navegación y demás actividades que se realicen en y/o a través del Sitio, son a cargo exclusivo de los Usuarios.</div>
                    <div className="term-text">La adquisición de ciertos productos y acceso a ciertos servicios puede estar sujeta a ciertas condiciones particulares (en adelante, las “Condiciones Particulares”). En tales casos, los Términos y Condiciones regirán todos aquellos aspectos que las Condiciones Particulares no contemplen. En el caso de que exista alguna inconsistencia y/o contradicción entre las Condiciones Particulares y los Términos y Condiciones, prevalecerán las Condiciones Particulares.</div>
                    <div className="term-text">El Usuario podrá participar de las promociones, sorteos, competencias, concursos y consignas (en adelante, las “Promociones”) que sean realizadas en el Sitio, organizadas por la Empresa y/o terceros anunciantes. El Usuario comprende y acepta que dicha participación quedará sujeta a los Términos y Condiciones y a las Condiciones Particulares que eventualmente se establezcan para cada Promoción. Estas últimas se considerarán aceptadas si el Usuario decide voluntariamente participar en una Promoción.</div>
                    <div className="term-text">La Empresa se reserva el derecho de modificar los Términos y Condiciones, así como la Política de Privacidad a su sola y exclusiva discreción, en cualquier momento, sin que ello dé lugar a indemnización y/o compensación alguna a favor del Usuario.</div>
                    <div className="term-text">Toda solicitud de actualización y/o supresión de la Información debe ser dirigida comunicada al 0800-22-CHELAS y/o a la siguiente dirección de correo electrónico contacto@chelas.com.ar indicando en el asunto del correo "Informar", "Rectificar", "Suprimir" y/o "Actualizar" según corresponda y proveyendo los datos necesarios para cumplir con el objeto del requerimiento.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">1. Prohibición de ingreso y uso del Sitio a menores de edad.</div>
                    <div className="term-text">SOLO PODRÁN ACCEDER, USAR, REALIZAR TRANSACCIONES Y/O DE CUALQUIER MANERA VINCULARSE CON EL SITIO, PERSONAS HUMANAS MAYORES DE 18 AÑOS, QUEDANDO PROHIBIDA TODA Y/O CUALQUIER ACTIVIDAD EN EL SITIO DE MENORES DE EDAD.</div>
                    <div className="term-text">La aceptación de estos Términos y Condiciones implica que los Usuarios aceptan en forma irrevocable las siguientes obligaciones.</div>
                    <div className="term-text">Conforme lo establecido por el art. 6 inciso A) de la ley 24.788 (LEY NACIONAL DE LUCHA CONTRA EL ALCOHOLISMO) los mensajes creados y/o actividades realizadas en y/o a través del Sitio no pueden tener como destinatarios a menores de 18 años.</div>
                    <div className="term-text">Si la declaración realizada por Usuario respecto de su edad fuera falsa o errónea, será exclusiva responsabilidad del Usuario y/o de los padres y/o tutores y/o responsables del Usuario. Los padres y/o tutores del Usuario pueden asimismo solicitar, frente a la declaración falsa o errónea realizada por un menor, que se elimine la información del respectivo Usuario de la base de datos de la Empresa. Para ello, deberá comunicarse con la Empresa a la siguiente dirección de correo electrónico: contacto@chelas.com.ar</div>
                    <div className="term-text">Los padres, tutores y/o responsables de los menores de 18 años que utilicen el Sitio son plena y exclusivamente responsables por el uso del Sitio por parte de éstos, incluyendo sin limitación, cualquier cargo o costo en que se pueda incurrir como consecuencia de tal uso.</div>
                    <div className="term-text">Los Usuarios serán los únicos responsables de la veracidad de todo y/o cualquier dato por ellos enviados al Sitio y por el envío de mensajes y/o cualquier contacto y/o comunicación del, hacia, y/o a partir del Sitio.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">2. Registro online.</div>
                    <div className="term-text">Para adquirir los productos ofrecidos en el Sitio, cada Usuario del Sitio debe registrarse y generar su cuenta. La información suministrada al registrarse (en adelante, los “Datos Personales”), se guardará en la base de datos de la Empresa y será utilizada para procesar el pedido con eficiencia y rapidez, además de facilitar las próximas compras.</div><div className="term-text">La Empresa no almacena los datos de tarjetas de crédito de los Usuarios (en adelante, los “Datos de Tarjeta”). Al momento de la efectivización de las transacciones en el Sitio, el Usuario será redirigido al Sitio de Mercado Pago en donde ingresará los Datos de Tarjeta y realizará los pagos correspondientes. En ese sentido, en el supuesto de que el Usuario desee modificar y/o suprimir sus Datos de Tarjeta, deberá solicitarlo directamente a Mercado Pago. La Empresa no será responsable frente al Usuario ni frente a ningún tercero por los daños, infracciones, delitos, contravenciones o cualquier otra clase de ílicitos que pudieran cometerse en relación a los Datos de Tarjeta. El Usuario solo podrá abonar su pedido con tarjeta de crédito y débito a través de Mercado Pago.</div><div className="term-text">Una vez realizados los pagos, el Usuario será redirigido nuevamente al Sitio</div><div className="term-text">Los Datos Personales recabados podrán ser utilizados para la participación en Promociones, ofertas y envío de comunicaciones de novedades, marketing y publicidad. La información brindada por el Usuario debe ser exacta y veraz para poder realizar la compra electrónica. La Empresa sugiere a los Usuarios del Sitio, revisar adecuadamente los Datos Personales brindados para el proceso de registro y compra. Los Usuarios garantizan y responden, en todo y cualquier caso, por la veracidad, exactitud, vigencia y autenticidad de los Datos Personales ingresados y/o brindados para su registro y/o al efectuar la compra. Además, los Usuarios deberán mantener debidamente actualizados dichos Datos Personales. Sin perjuicio de ello, la Empresa podrá solicitar más información a fin de verificar la autenticidad o veracidad de los Datos Personales y/o de la actividad y/o transacción que se intente realizar en el Sitio. Por lo tanto, la Empresa no responderá por ninguna consecuencia derivada del incumplimiento por parte del Usuario de las obligaciones que éste asume en relación a los Datos Personales.</div>
                    <div className="term-text">Los Datos Personales serán utilizados por la Empresa, sus controlantes y/o empresas vinculadas, conforme las finalidades y modalidades expuestas en estos Términos y Condiciones y en la Política de Privacidad y/o en las Condiciones Particulares según el caso.</div><div className="term-text">Es responsabilidad exclusiva de los Usuarios resguardar la confidencialidad de las claves utilizadas para el registro y acceso al Sitio, así como de los Datos de Tarjeta, debiendo mantenerlas en secreto, para su uso personal y sin acceso de terceros, quedando prohibida toda y/o cualquier forma de transferencia y/o cesión.</div><div className="term-text">Los Usuarios entienden que toda compra que se efectúe con los Datos de Tarjeta proporcionando la clave de seguridad debe entenderse como realizada en nombre del Usuario, pudiendo la Empresa considerar que las operaciones derivadas son válidas, legítimas y auténticas sin necesidad de realizar o tomar ningún otro resguardo. El Usuario asume la total responsabilidad por extravío, robo o hurto de la tarjeta de crédito habilitada para el servicio. En ese sentido, en caso de pérdida o robo de la tarjeta de crédito registrada, el Usuario se compromete a comunicarlo inmediatamente al emisor de la tarjeta a efectos de denunciar el hecho y proceder a la baja de la tarjeta de crédito y la consecuente remoción de los Datos de Tarjeta. Todas las operaciones realizadas con anterioridad a dicha comunicación que estuvieren perfeccionadas con los Datos de Tarjeta proporcionados se considerarán válidas y a cargo del Usuario exclusivamente.</div><div className="term-text">Los Usuarios son los únicos responsables de todo y/o cualquier uso y/o transacción realizada con y/o a través de sus cuentas en y/o a través del Sitio. Sin perjuicio de ello, la Empresa podrá rechazar las actividades y/o transacciones cuando, a su criterio, existan indicios de que la cuenta está siendo utilizada sin autorización del Usuario Titular, sin que ello implique responsabilidad alguna de la Empresa.</div><div className="term-text">Los Usuarios se obligan a dar inmediato y fehaciente aviso a la Empresa mediante correo electrónico a contacto@chelas.com.ar, en caso de usos no autorizados de sus cuentas, así como el ingreso por terceros no autorizados a la misma.</div>
                    <div className="term-text">La Empresa se reserva el derecho a rechazar los pedidos de registro, y/o suspender y/o dar de baja a todo Usuario registrado, sin que ello genere responsabilidad de la Empresa ni derecho a reclamo de ninguna índole, en cualquiera de los siguientes casos: (i) uso irregular de la cuenta; (ii) incumplimiento de los Términos y Condiciones, la Política de Privacidad, las Condiciones Particulares y el orden legal aplicable; (iii) rechazo de los pagos ingresados; e (iv) ingreso de Datos Personales incompatibles.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">3. Confidencialidad de los Datos Personales.</div>
                    <div className="term-text">En el marco de la Política de Privacidad, la Empresa mantendrá en absoluta confidencialidad la totalidad de los Datos Personales suministrados por los Usuarios del Sitio, salvo en los casos en los que la Ley de Protección de Datos Personales permite su divulgación.</div><div className="term-text">Para mayor detalle ver las Políticas de Privacidad.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">4. Funcionamiento del Sitio.</div>
                    <div className="term-text">La Empresa podrá, sin necesidad de notificación previa, determinar la suspensión, modificación y/o terminación del Sitio; por lo que no será responsable frente al Usuario ni frente a ningún tercero por ningún concepto, ante cualquiera de estas circunstancias. La Empresa es libre de limitar el acceso al Sitio y/o a los productos en él ofrecidos a los Usuarios sin necesidad de justificación ni notificación previa.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">5. Obligaciones del Usuario con relación al uso del Sitio.</div>
                    <div className="term-text">El Usuario se compromete a cumplir con toda la normativa aplicable y es el único responsable de toda la actividad de su cuenta, registro o contraseña, y con relación a la información o material que incluya en el Sitio.</div>
                    <div className="term-text">El Usuario no realizará ni promoverá cualquiera de las siguientes acciones y/o conductas en o a través del Sitio:</div>
                    <div className="term-text">(i) Actividades ilícitas, ilegales o contrarias a la buena fe, la moral y al orden público.</div>
                    <div className="term-text">(ii) Difusión, publicación, distribución y/o divulgación de contenidos, mensajes, información y/o propaganda ilegales, tales como aquellos que tengan contenidos o connotaciones racistas, xenófobas, discriminatorias por cuestiones de raza, religión, preferencias o tendencias sexuales u opiniones políticas, de apología de delitos, terrorismo, atentatorios contra los derechos humanos, pornográficos, obscenos, afecten los derechos y/o la identidad de menores y/o difamatorios, así como tampoco difamar, insultar, acosar, acechar, amenazar o infringir de cualquier otra forma los derechos de terceros.</div>
                    <div className="term-text">(iii) Alterar, modificar, interferir o interrumpir y/o dañar el Sitio, los equipos de computación (hardware), programas de computación (software) y/o equipos y/o sistemas de telecomunicaciones y/o distribución de Datos Personales, sean de la Empresa, otros Usuarios y/o de sus proveedores en cualquier forma y/o por cualquier medio y, en general, a realizar cualquier conducta que afecte o dañe los intereses de la Empresa y/o de los Usuarios en modo alguno.</div>
                    <div className="term-text">(iv) Introducir o difundir virus informáticos, troyanos, bugs, spyware, malware y/o cualquier tipo de archivo, programa y/o dato que sean susceptibles de provocar daños de cualquier tipo y/o en cualquier bien y/o propiedad en el Sitio.</div>
                    <div className="term-text">(v) Utilizar o lanzar cualquier sistema automatizado, incluyendo, sin limitar, robots, "arañas" o “spiders” y/o "lectores fuera de línea" u “offline readers”, que accedan al Sitio, de forma tal que generen un tráfico con los servidores utilizados por la Empresa que exceda el que un Usuario podría razonablemente producir, utilizando para ello un navegador convencional. Ello, sin perjuicio de la autorización especial que la Empresa concede a los responsables de motores públicos de búsqueda con el único propósito de crear índices de búsqueda que permitan a sus usuarios localizar el Sitio.</div>
                    <div className="term-text">(vi) Recolectar u obtener del Sitio información personal identificable de otros Usuarios o utilizar los sistemas de comunicación disponibles en el Sitio para contactar a otros Usuarios con fines comerciales, excepto en aquello que esté autorizado por la Política de Privacidad, Términos y Condiciones y las Condiciones Particulares.</div><div className="term-text">(vii) Acceder al Sitio, usando tecnologías y/o medios distintos a los utilizados y/o autorizados por la Empresa.</div>
                    <div className="term-text">(viii) Evitar, inhabilitar y/o interferir en cualquier forma con los programas, utilidades, aplicaciones y/o funciones relacionadas con la seguridad o el uso y/o acceso no autorizado del Sitio.</div>
                    <div className="term-text">La comisión de conductas prohibidas dará lugar a que la Empresa suspenda o cancele el registro del Usuario y la habilitación de la cuenta, sin perjuicio de las acciones legales penales o civiles que pudieran corresponder.</div>
                    <div className="term-text">El Usuario será responsable de conocer la tecnología que está utilizando y las características de su navegador para tomar las decisiones de navegación.</div>
                    <div className="term-text">El Usuario presta conformidad y se compromete a indemnizar y mantener indemne a la Empresa y/o a cualquiera de sus funcionarios, dependientes, licenciantes, proveedores y licenciatarios, de y contra toda pérdida, gasto, daño, perjuicio, costos, honorarios y, en general (cualquiera sea la naturaleza o alcance de los mismos, incluyendo pero no limitados a daños directos o indirectos, inmediatos o mediatos, daño emergente, lucro cesante, pérdida de chance y/o daño moral (en adelante, los “Daños”) que se originen por cualquier violación a las leyes y normas aplicables y/o a los Términos y Condiciones y/o derivadas del mal uso del Sitio, sea que las mismas se concreten por acción u omisión, en los que incurra el Usuario.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">6. Compra y alquiler de Productos. Procedimientos.</div>
                    <div className="term-text">El Usuario sólo podrá adquirir los productos si se encuentra debidamente registrado y ha generado una cuenta conforme los Términos y Condiciones.</div>
                    <div className="term-text">Podrán adquirir productos conforme a los procedimientos que a continuación se detallan, aquellos Usuarios que sean consumidores finales.</div>
                    <div className="term-text">Las imágenes y/o representación de los productos en el Sitio son al solo efecto ilustrativo del Usuario.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">6.1. Procedimiento de compra para Usuarios consumidores finales.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">6.1.1. Condiciones Generales.</div>
                    <div className="term-text">Las condiciones de compra que se apliquen a cada transacción serán las publicadas al momento de realizar la transacción. En tal oportunidad, el Usuario deberá aceptar las condiciones generales de venta y entrega que son especificadas en estos Términos y Condiciones, la descripción de los productos ofrecidos y el precio publicado. La Empresa se compromete a gestionar los pedidos siempre que los productos y/o artículos requeridos por el Usuario estén disponibles en stock, de acuerdo con lo informado en el Sitio. Toda transacción queda sujeta a la confirmación de la misma por parte de la Empresa, la que será realizada mediante la remisión al Usuario de un correo electrónico a la casilla declarada al momento del registro.</div>
                    <div className="term-text">Los productos y artículos que se deseen adquirir deberán ser seleccionados y añadidos al carrito de compras haciendo “click” sobre el botón de comprar. Una vez hecho esto el Usuario accederá a su carrito de compras y podrá visualizar el detalle de su compra que contendrá el/los número/s del artículo/s seleccionado/s, nombre, y/o todo otro dato necesario para su identificación y el precio final correspondiente. Una vez que el Usuario verifique los datos suministrados, podrá proceder a la compra de los mismos completando la información de dirección de envío e información de pago correspondiente. En tanto y cuando se confirme la transacción, la Empresa comunicará al Usuario a través de correo electrónico el número de orden del pedido con el detalle de su compra, así como también lo mantendrá al tanto vía email del estado de su pedido.</div>
                    <div className="term-text">La compra de productos y artículos ofrecidos en el Sitio se encuentra sujeta a disponibilidad de stock, sin derecho a reclamo de ninguna índole en caso de agotarse el mismo.</div><div className="term-text">Los productos y/o los precios, ofrecidos en el Sitio no necesariamente coincidirán con los productos y/o precios ofrecidos en otros locales o puntos de venta.</div>
                    <div className="term-text">El Usuario podrá adquirir un máximo de 5 unidades de bebidas, ya sea compradas de manera individual o dentro de un pack.</div>
                    <div className="term-text">El Usuario acepta y reconoce que, si la Empresa toma conocimiento de que las limitaciones fijadas en estos Términos y Condiciones han sido violadas por parte del Usuario, la Empresa podrá, a su sola discreción, dejar sin efecto la compra efectuada por éste siempre que notifique el motivo por el cual la compra fue dejada sin efecto.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">6.1.2. Precio</div>
                    <div className="term-text">Todos los precios del Sitio están formulados en pesos argentinos ($AR) e incluyen el Impuesto al Valor Agregado (I.V.A.), pero no el costo de envío, que se calculará en función del monto de la compra y la localización informada por el Usuario al momento de concluir el procedimiento de compra del Sitio. Los precios serán fijados por la Empresa, quien se reserva el derecho de modificarlos y/ o cambiarlos, en cualquier momento, lo cual será publicado en el Sitio.</div>
                    <div className="term-text">Las Promociones no serán acumulativas. Las ofertas y Promociones sólo tendrán validez para los pedidos efectuados a partir de la fecha de vigencia de la misma y hasta la fecha de finalización de la misma.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">6.1.3. Condiciones de Pago.</div>
                    <div className="term-text">Los medios de pago disponibles son provistos por Mercado Pago, propiedad de Mercado Libre S.R.L., CUIT 30-70308853-4. Las compras con tarjeta de crédito pueden realizarse en pagos de una cuota o bien en cuotas de acuerdo a las promociones ofrecidas por Mercado Pago.</div><div className="term-text">Las metodologías de pago quedan sujetas a modificaciones conforme al servicio provisto por Mercado Pago, cuyos términos y condiciones deben ser aceptados por el comprador.</div><div className="term-text">Ante cualquier duda puede usar nuestro e-mail de contacto contacto@chelas.com.ar o bien contactando a nuestro centro de ayuda en línea desde el sitio.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">6.1.4.&nbsp;Desconexión al Sitio.</div>
                    <div className="term-text">Ante eventuales desconexiones y/o cortes y/o interrupciones por motivos de mantenimiento del Sitio y/o por sucesos, y/o hechos y/o acontecimiento de cualquier naturaleza que se encuentren fuera del alcance o control de la Empresa, se recomienda al Usuario contactar a la Empresa al email contacto@chelas.com.ar para poder solucionar el problema con la mayor eficiencia posible.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">6.1.5. Envío.</div>
                    <div className="term-text">El Usuario deberá pagar el envío cuyo valor será adicionado al precio y deberá ser consultado en el Sitio. El valor del envío estará relacionado con el destino del mismo. Los tiempos de envío serán los indicados en el Sitio. La Empresa podrá a su exclusivo criterio en forma temporal y/o permanentemente resolver la bonificación gratuita del envío en cuyo caso publicará tal información en el Sitio.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">6.1.6. Cambio de Producto. Devoluciones.</div>
                    <div className="term-text">El Usuario tiene derecho a revocar cualquier operación comercial realizada en el Sitio por adquisición de productos durante el plazo de DIEZ (10) días corridos, contados a partir de la fecha en que se entregue el producto o se celebre el contrato, lo último que ocurra. Si el plazo vence en día inhábil, se prorroga hasta el primer día hábil siguiente. Esta facultad no puede ser dispensada ni renunciada. El Usuario comunicará fehacientemente dicha revocación a la Empresa y pondrá el/los productos/s a su disposición. Los gastos de devolución son por cuenta de la Empresa. Para ejercer el derecho de revocación el Usuario deberá poner el producto a disposición de la Empresa sin haberla usado y manteniéndola en el mismo estado en que la recibió, debiendo restituir la Empresa al Usuario los importes recibidos en concepto de precio, a través del mismo medio de pago utilizado para realizar la operación.</div>
                    <div className="term-text">A tal efecto, el Usuario podrá revocar su aceptación y cancelar la compra dentro el plazo establecido, haciendo click en el Botón de Arrepentimiento ubicado en la parte inferior del Sitio, completando únicamente el código de pedido o número de orden que le fuere enviado por correo al momento de compra y confirmando la revocación.</div>
                    <div className="term-text">Dentro de las 24 horas de solicitada la cancelación, la Empresa le enviará al Usuario un email de confirmación con el número de solicitud de arrepentimiento generado y las instrucciones para proceder a la devolución.</div><div className="term-text">En cualquier caso, la solicitud de cambio y/o devolución también podrá realizarse enviando un email a la casilla: contacto@chelas.com.ar El Usuario será el único responsable de devolver el producto que La Empresa entregó oportunamente, en el mismo estado en que la recibió, junto con sus etiquetas, embalaje y accesorios originales, todos en perfecto estado de conservación. En ningún caso se podrá realizar la devolución de productos abiertos ni cuyos envases se encuentren dañados (roturas ni abolladuras). La devolución de un producto distinto al entregado habilitará a la Empresa a realizar los reclamos correspondientes al Usuario, sin perjuicio de los daños y perjuicios que podrá reclamar ante las vías administrativas y judiciales. El Usuario será el único responsable por todos los daños y perjuicios que la entrega de un producto distinto al entregado oportunamente por la Empresa genere a esta última y/o a cualquier tercero. Si al recibir el producto, la Empresa constata que el/los productos/s no se encuentran en su embalaje original o que se ha dañado o faltan accesorios por causas imputables al Usuario, se deducirá del valor cancelado originalmente por el producto, un porcentaje equivalente al costo que la Empresa deba incurrir para dejarlo en óptimas condiciones.</div><div className="term-text">Transcurrido este plazo, la Empresa se reserva el derecho de aceptar o no el cambio del producto. Quedan expresamente exceptuados del derecho de revocar aquellos Usuarios que compren a través del Sitio productos que por su naturaleza no puedan ser devueltos o puedan deteriorarse con rapidez.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">7. Indemnidad</div>
                    <div className="term-text">El Usuario se obliga en forma expresa e irrevocable a mantener absolutamente indemne a la Empresa y/o sus sociedades vinculadas, respecto a cualquier reclamo y/o demanda y/o sanción extrajudicial, administrativo o judicial, de cualquier tercero, derivada del uso del Sitio por parte del Usuario, o en caso de verificarse la existencia de multas y/o deudas de cualquier tipo generadas por el Usuario o la actividad del mismo realizada en o mediante el Sitio.</div>
                    <div className="term-text">El Usuario acepta que el uso del Sitio se realiza bajo su propia, exclusiva y única responsabilidad. La Empresa no se responsabiliza por ningún daño o perjuicio, directo o indirecto, incluyendo sin ningún tipo de limitación Daños producidos por las pérdidas o deterioros de la información, ni por las demoras, interrupciones y defectos que pudieran existir en las transmisiones, mediante la utilización del Sitio, así como tampoco de los virus o fallas del sistema, siempre que ello no sea imputable a la Empresa.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">8. Links desde y hacia sitios de terceros.</div>
                    <div className="term-text">El Sitio puede contener vínculos o links desde o hacia sitios de internet que son de propiedad o están bajo el control de terceros y que no son propiedad ni son controlados por la Empresa (en adelante, los “Sitios de Terceros”). La existencia de estos vínculos o links no implica que exista alguna clase de sugerencia, invitación o recomendación para la visita de los Sitios de Terceros o ninguna clase de asociación entre la Empresa y los Sitios de Terceros. La Empresa no tiene control alguno sobre los Sitios de Terceros ni sus contenidos, ni los censura o edita. La Empresa no emite declaración ni otorga garantía alguna por el contenido, servicios, términos y condiciones de uso, políticas de privacidad y/o prácticas de los Sitios de Terceros y, por lo tanto, no asume responsabilidad alguna. La Empresa recomienda que cada vez que se siga un link o vínculo a un Sitio de Tercero, el Usuario, lea los términos y condiciones de uso y las políticas de privacidad del sitio que está visitando o accediendo. El Usuario asume todos los riesgos asociados con el uso de cualquier contenido y/o servicios provisto por los Sitios de Terceros.</div>
                    <div className="term-text">La Empresa recomienda al Usuario ser discreto al brindar Información al utilizar estos servicios, ya que la Información o datos brindados a través de los mismos podrían ser recopilados o utilizados por terceros para fines no autorizados por el Usuario. La Empresa no será responsable del uso y/o tratamiento que se le dé a la información que los Usuarios proporcionen al participar de los servicios abiertos al público, ni tampoco tendrá acceso a la información que estos terceros conserven y mantengan en sus bases de datos.</div>
                    <div className="term-text">De conformidad con lo expuesto precedentemente, la Empresa no garantiza, recomienda, patrocina ni asume responsabilidad alguna por los productos y/o servicios promocionados u ofrecidos en o a través de los Sitios de Terceros.</div>
                    <div className="term-text">El Usuario acepta que el acceso y uso de los Sitios de Terceros será bajo exclusiva responsabilidad del Usuario y que, en consecuencia, el Usuario libera expresamente a la Empresa de toda responsabilidad por los Daños o consecuencia derivada del uso que el Usuario haga de dichos sitios.</div>
                    <div className="term-text">La Empresa prohíbe la presentación de cualquier parte del Sitio en una ventana de un Sitio de Terceros ("framing") y la inserción de contenidos a través de Sitios de Terceros (“in line linking”) que no haya sido previa y expresamente autorizado por la Empresa por escrito.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">9. Limitación de Responsabilidad.</div>
                    <div className="term-text">El Usuario comprende y acepta las características y los riesgos propios de la conexión y navegación por Internet. Por lo tanto, la Empresa no será responsable por fallas, interrupciones y/o caídas de la red y/o de los servicios de conexión y/o transmisión de datos, ni tampoco garantiza el acceso al Sitio en forma ininterrumpida, precisa o sin errores (siempre que ello no se derive de causas que le resulten imputables) y, por lo tanto, la Empresa no responderá por los Daños que eventualmente el Usuario pueda llegar a sufrir por dichas circunstancias.</div>
                    <div className="term-text">La Empresa se reserva el derecho a modificar los programas de computación, aplicaciones y/o sistemas operativos que utiliza, la sistematización y/o la presentación general, así como las características y/o condiciones de acceso y/o uso del Sitio. Igualmente, la Empresa se reserva el derecho de modificar, interrumpir, suspender y/o cancelar en forma temporaria, definitiva, parcial y/o total las características, alcances, datos, uso, disponibilidad y/o acceso al Sitio, por razones técnicas, comerciales, actualización, mantenimiento, contractuales y/o de conveniencia sin necesidad de justificación ni notificación previa.</div>
                    <div className="term-text">La Empresa no será responsable por los Daños y perjuicios –cualquiera sea su naturaleza o extensión- que eventualmente sufra el Usuario derivado de la conexión, acceso, visita y/o uso a los Sitios de Terceros y/o los contenidos y/o servicios prestados a través de los mismos.</div>
                    <div className="term-text">La Empresa no será responsable por cualquier cambio y/o modificación en los Términos y Condiciones y/o la Política de Privacidad.</div>
                    <div className="term-text">La Empresa en ningún caso será responsable en cuanto a las informaciones, datos, opiniones y conceptos que los Usuarios emitan, publiquen o distribuyan directa e indirectamente a través del Sitio y/o por los que emitan, publiquen o distribuyan mediante los Sitios de Terceros.</div>
                    <div className="term-text">La Empresa usa antivirus y protección contra virus, bugs, troyanos, malware, spyware y otros riesgos en Internet (en adelante, los “Riesgos”). Sin embargo, ello no podría ser suficiente y no releva al Usuario de la responsabilidad de contar con sus propios métodos de protección para una navegación, acceso y uso seguro de sitios de Internet. Por lo tanto, La Empresa no se responsabiliza por Daños ocasionados por los Riesgos y/o todo otro daño derivado del acceso y/o uso del Sitio. La Empresa tampoco asume responsabilidad alguna por el acceso o uso no autorizado de los servidores utilizados para el alojamiento del Sitio y/o los datos de los Usuarios por parte de terceros.</div>
                    <div className="term-text">La Empresa utiliza el sistema de seguridad cifrado por SSL, capa de conexión segura, para encriptar los datos de los Usuarios cargados en el Sitio.</div>
                    <div className="term-text">Sin embargo, resulta importante señalar que no se puede garantizar la seguridad de la información ni de los pagos que se transmiten por Internet o por correo electrónico, no siendo la Empresa y/o sus licenciantes y/o sociedades vinculadas en ningún caso, responsables de los Daños que eventualmente deriven del uso de medios de comunicación electrónicos, incluyendo, pero sin limitarse a ellos, los Daños que se deriven de un fallo o retraso en el envío de comunicaciones electrónicas, intercepción o manipulación de comunicaciones electrónicas por parte de terceros o mediante programas informáticos utilizados para la transmisión de comunicaciones electrónicas o de virus.</div>
                    <div className="term-text">Asimismo, la Empresa no será responsable frente al Usuario ni frente ningún tercero por los Daños, infracciones, delitos, contravenciones o cualquier otra clase de ilícitos que pudieran cometerse, ya se trate de derechos de propiedad intelectual, al honor y reputación de las personas, sus datos personales, crediticios, derechos del consumidor, ni cualquier otro derecho que pudiera ser vulnerado como consecuencias del mal uso del Sitio por parte de los Usuarios.</div>
                    <div className="term-text">Las limitaciones a la responsabilidad de la Empresa establecidas en el presente apartado alcanzan también a los directores, administradores, representantes, funcionarios, empleados y/o asesores de la Empresa, los que también quedan liberados de cualquier responsabilidad en relación con el uso y/o acceso al Sitio que realicen los Usuarios y terceros por los que no deben responder.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">10. Derechos de Propiedad Intelectual e Industrial.</div>
                    <div className="term-text">La Empresa mantiene una política clara en relación a la protección y defensa de derechos de propiedad intelectual e industrial (incluyendo, pero no limitado a derechos de autor, marcas, patentes, diseños y modelos industriales tanto propios como de terceros).</div>
                    <div className="term-text">La Empresa es el titular exclusivo de todos los derechos sobre el Sitio. Todos los contenidos y los signos distintivos utilizados en el Sitio (incluyendo, pero no limitado a datos, textos, marcas, iconos, obras musicales y audiovisuales, imágenes, diseño o "look and feel" del Sitio, bases de datos, índices, programas de computación, otras aplicaciones informáticas, material publicitario o promocional y/o todo otro tipo de obras en general (en adelante, los “Derechos”) son propiedad de La Empresa o de sus licenciantes o de sus respectivos titulares de los derechos de propiedad intelectual y/o industrial (en adelante, los Titulares de Derechos). Por lo tanto, el Usuario reconoce y acepta que la Empresa y/o los Titulares de Derechos, son los propietarios de todos los derechos, títulos e intereses sobre el Sitio, independientemente de las circunstancias sobre su registro o depósito y/o la jurisdicción en la que los mismos hayan sido comenzados a utilizar, explotar o hayan sido depositados y/o registrados. El uso y/o acceso al Sitio, no atribuyen al Usuario licencia o facultad alguna sobre los Derechos y/o el Sitio, más allá de lo que expresamente se disponga para el correcto uso del Sitio. El uso indebido y la reproducción total o parcial de dichos contenidos quedan prohibidos, salvo autorización expresa y por escrito de su titular.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">11. Aceptación de los Términos y Condiciones.</div><div className="term-text">Deberá abstenerse de operar en el Sitio toda persona que no acepte estos Términos y Condiciones, los cuales tienen carácter obligatorio y vinculante. El Usuario será responsable por todas las operaciones efectuadas en su cuenta. La Empresa no se responsabiliza por la mala utilización del Sitio que hicieran los Usuarios y otros terceros por los que no deba responder. La Empresa podrá modificar los Términos y Condiciones en cualquier momento, los que deberán ser nuevamente expresamente aceptados por el Usuario para poder hacer uso del Sitio.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">12. Único Acuerdo.</div>
                    <div className="term-text">Los Términos y Condiciones y sus modificaciones, así como la Política de Privacidad, constituyen el único acuerdo entre el Usuario y la Empresa y reemplaza cualquier contrato previo entre ambos. Asimismo, el Usuario también estará sujeto a Condiciones Particulares se establezcan.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">13. Contacto de la Empresa.</div>
                    <div className="term-text">Toda solicitud, consulta, reclamo y, en general, cualquier comunicación a la Empresa deberá ser cursada por correo electrónico a la siguiente dirección: contacto@chelas.com.ar.</div>
                    <div className="term-spacer"></div>
                </div>
                <div>
                    <div className="term-subtitle">14. Ley aplicable. Jurisdicción.</div>
                    <div className="term-text">Los Términos y Condiciones así como la relación entre el Usuario y la Empresa serán interpretados y estarán regidos por las leyes de la República Argentina.</div>
                    <div className="term-text">Conoce las normas que aplican cuando compras: <a href="http://servicios.infoleg.gob.ar/infolegInternet/anexos/0-4999/638/texact.htm" className="css-j01ua9-text-link">Ley N° 24.240 de Defensa del Consumidor.</a>
                </div>
            </div>
            <div>
                <div className="css-0"></div>
                <div className="term-text">Consumo Protegido: consumoprotegido@mecon.gob.ar</div>
            </div>
            <div>
                <div className="css-0"></div>
                <div className="term-text">Defensa de las y los Consumidores: Para reclamos ingrese 
                    <a href="https://www.argentina.gob.ar/produccion/defensadelconsumidor/formulario" className="css-j01ua9-text-link">aquí.</a>
                </div>
            </div>
            <div>
                <div className="css-0"></div>
                <div className="term-text">Ciudad Autónoma de Buenos Aires: Dirección General de Defensa y Protección al Consumidor, para consultar y/o denuncias ingrese 
                        <a href="https://www.buenosaires.gob.ar/defensaconsumidor" className="css-j01ua9-text-link">aquí.</a>
                </div>
            </div>
            <div>
                <div className="css-0"></div>
                <div className="term-text">Cualquier cláusula o condición de este documento que, por cualquier razón, sea reputada nula o ineficaz por cualquier juicio o tribunal, no afectará la validez de las demás disposiciones de estos Términos, las cuales permanecerán plenamente válidas y vinculantes, generando efectos en su máxima extensión. La falla de la Empresa en exigir cualquier derecho o disposición de los presentes Términos no constituirá renuncia, pudiendo ejercer regularmente su derecho, dentro de los plazos legales. En caso de dirimir cualquier duda, cuestiones o litigios derivados de los presentes Términos serán de aplicación como resolución de disputa los Tribunales Ordinarios de la Ciudad de Buenos Aires, renunciando a las partes a cualquier otro, por más privilegiado que sea. </div>
                <div className="term-text">Última actualización: 15 de abril de 2021.</div>
            </div>
        </div>
        </>
    )
};

export default Terminos;